version: '3.8'

services:


  mongo:
    container_name: mongo_v3

    image: mongo
    ports:
      - 27017:27017

    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: attia
      MONGO_INITDB_ROOT_PASSWORD: attia
    networks:
      - microservices-net

  mongo-express:
    container_name: mongo-express_v3
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:

      ME_CONFIG_MONGODB_ADMINUSERNAME: attia
      ME_CONFIG_MONGODB_AUTH_PASSWORD: attia
      ME_CONFIG_MONGODB_URL: mongodb://attia:attia@mongo:27017/
      ME_CONFIG_BASICAUTH: false


    networks:
      - microservices-net
    depends_on:
      - mongo








networks:
  microservices-net:
    driver: bridge

